name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binaries as artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: "lazycrate-linux-x86_64"
        path: "target/release/lazycrate"
        if-no-files-found: error
        retention-days: 7
